### PR TITLE
fs.exists() should return True for common prefixes

### PR DESCRIPTION
**Pull request by ozkatz**
Similar to s3fs, `fs.exists()` should return True also for common prefixes.
Ran into this while trying to use lakefs-spec with [HuggingFace Datasets](https://huggingface.co/docs/datasets/en/index) - loading a dataset accepts a directory uri, which is checked for existence and subsequently fails.

The check is done in a similar fashion to [s3fs'](https://github.com/fsspec/s3fs/blob/main/s3fs/core.py#L1397) - ensure path ends with `'/'`, attempt listing, return True if there's anything under that prefix.

### CODE REVIEW

**Comment by ozkatz** [comment]
@nicholasjng @AdrianoKF Hope this change meets the contribution guidelines, happy to change as needed.

**Comment by nicholasjng** [comment]
Looks good! I'm only wondering about exceptions - can the exists() call throw in any non-trivial (i.e. other than connection/permission errors) situation, meaning we wouldn't get to decide the prefix question?

**Comment by ozkatz** [comment]
Thanks @nicholasjng - good question :) I don't think calling `objects()` increases the surface area for that. 

You're already handling server errors, which is the right thing to do - this should also handle any unexpected errors from listing objects.

**Review by nicholasjng — APPROVED** [review]
Nice! Please squash to a single commit, then we can get this in :)

**Comment by ozkatz** [comment]
@nicholasjng done :)

**Comment by nicholasjng** [comment]
Thank you!

**Comment by ozkatz** [comment]
@nicholasjng any estimation as to when we can expect a next release?

**Comment by nicholasjng** [comment]
@ozkatz I can release today if it's urgent, but if anything goes wrong, it takes until Tuesday at minimum.

**Comment by ozkatz** [comment]
Tuesday is absolutely fine :) thank you @nicholasjng !!

**Pull request merged**
